/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.Actions;
import controller.Controller;
import java.util.HashSet;
import java.util.Set;
import models.Actividad;
import models.ManejadorActividades;

/**
 *
 * @author Pedro
 */
public class CreateActividad extends javax.swing.JDialog {

    /**
     * Creates new form CreateActividad
     */
    public CreateActividad(Controller controller) {
        initComponents();
        jButton1.addActionListener(controller);
        jButton1.setActionCommand(Actions.CREATE.name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPredecesor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerPesimista = new javax.swing.JSpinner();
        jSpinnerOptimista = new javax.swing.JSpinner();
        jSpinnerProbable = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Tiempo Pesimista");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 230, 90, 30);

        jLabel2.setText("Nombre Actividad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 50, 90, 30);

        jLabel3.setText("Predecesor");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 100, 90, 30);

        jLabel4.setText("Tiempo Optimista");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 140, 90, 30);

        jLabel5.setText("Tiempo Probable");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 180, 90, 30);
        jPanel1.add(jTextFieldName);
        jTextFieldName.setBounds(180, 60, 130, 20);
        jPanel1.add(jTextFieldPredecesor);
        jTextFieldPredecesor.setBounds(180, 100, 130, 20);

        jLabel6.setText("Agregar Informacion");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 10, 110, 30);
        jPanel1.add(jSpinnerPesimista);
        jSpinnerPesimista.setBounds(180, 230, 130, 20);
        jPanel1.add(jSpinnerOptimista);
        jSpinnerOptimista.setBounds(180, 140, 130, 20);
        jPanel1.add(jSpinnerProbable);
        jSpinnerProbable.setBounds(180, 180, 130, 20);

        jButton1.setText("CREAR");
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 270, 150, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

 
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerOptimista;
    private javax.swing.JSpinner jSpinnerPesimista;
    private javax.swing.JSpinner jSpinnerProbable;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPredecesor;
    // End of variables declaration                   


public Actividad createactividad(){
    Set<Character> info = new HashSet<Character>();
    String aux = jTextFieldPredecesor.getText().replaceAll(" +", "").toUpperCase();
    for (int i = 0; i < aux.length(); i++) {
          info.add(aux.charAt(i));
    }
    return ManejadorActividades.createActividad(jTextFieldName.getText().toUpperCase(), info, (int)jSpinnerOptimista.getValue(), (int)jSpinnerProbable.getValue(), (int)jSpinnerPesimista.getValue());
}

}
