/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 * @author pedro aguirre arias
 * @author julian david Grijalba
 */
public class Help extends JDialog {

    /**
     * Creates new form Help
     */
    public Help() {
        setIconImage(new ImageIcon(getClass().getResource("/imgs/icon.PNG")).getImage());
        initComponents();
        setSize(450, 400);
        setModal(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setBackground(new java.awt.Color(56, 100, 238));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/image1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 330, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Elaborado por: Pedro Aguirre Arias");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(108, 67, 213, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Universidad pedagogica y tecnologica de colombia- U P T C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 340, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Docente: Ingeniero: FREDDY ALBAN VARGAS HOLGUIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 158, 349, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Derechos de autor reservados");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(114, 186, 273, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("INVESTIGACION DE OPERACIONES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(87, 221, 227, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tunja. 07 de Junio de 2017");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(114, 256, 273, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Coreos: pedro.aguirre@uptc.edu.co");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(102, 279, 196, 15);

        jLabel9.setText("Telefono: 3102111183");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(134, 327, 196, 25);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Julian David Grijalba");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 90, 120, 26);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("julian.grijalba@uptc.edu.co");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(142, 301, 156, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
